In [28]:
from random import randint
import numpy as np
from PIL import Image, ImageDraw
import os
images = []
imagecodes = []
def listdir(path, list_name,filename):  #传入存储的list
    for file in os.listdir(path):  
        file_path = os.path.join(path, file)  
        if os.path.isdir(file_path):  
            listdir(file_path, list_name,file)  
        else:
            images.append(np.array(Image.open(file_path)))
            imagecodes.append(filename)
            list_name.append(file_path)
    return images, imagecodes

In [30]:
images, imagecodes = listdir("images/train",[],"")
print(images)
print(imagecodes)

[array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]

In [31]:
def preprocess_images(image_array):
    from PIL import Image, ImageOps
    
    # Pre-process all of the images to make them consistent
    images = []
    for img in image_array:
        # Equalize the pixel intensity to ensure consistent contrast
        img = ImageOps.equalize(Image.fromarray(img))
        # flatten the images
        images.append(np.array(img).ravel())
        
        # (our images are all the same size - otherwise you should resize them!)
        
    return images

# The pre-processed images are our features, the imagecodes are the labels
import numpy as np
features = np.array(preprocess_images(images))
print(features)
labels = np.array(imagecodes)
print(labels)
print(labels.size, 'cases ready for training.')

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 168 156 169]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
['axes' 'axes' 'axes' ... 'tents' 'tents' 'tents']
1712 cases ready for training.


In [32]:
# split into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size=0.30)

print('Training records:',Y_train.size)
print('Test records:',Y_test.size)

Training records: 1198
Test records: 514


In [33]:
# Train the model
from sklearn.linear_model import LogisticRegression

# Set regularization rate
reg = 0.01

# train a logistic regression model on the training set
clf = LogisticRegression(C=1/reg, solver='lbfgs', multi_class='multinomial').fit(X_train, Y_train)
print (clf)

LogisticRegression(C=100.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)


In [34]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

predictions = clf.predict(X_test)
print('Accuracy: ', accuracy_score(Y_test, predictions))

Accuracy:  0.8346303501945526


In [47]:
from random import randint
from PIL import Image, ImageOps

# Create a random test image
# img = create_image ((128,128), classnames[randint(0, len(classnames)-1)])
# plt.imshow(img)

# Modify the image data to match the format of the training features
imgfeatures = np.array(ImageOps.equalize(Image.open('data/31dc5-COk7L._AC_US436_QL65_.jpg'))).ravel().reshape(1, -1)

pred = clf.predict(imgfeatures)
print('The image is a',pred[0])

The image is a carabiners
